package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BuyingpointsTest {

  private WebDriver chromeDriver, firefoxDriver;
  JavascriptExecutor jsChrome, jsFirefox;
  private Map<String, Object> vars;
  @Before
  public void setUp() {
    chromeDriver = new ChromeDriver();
    chromeDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    firefoxDriver = new FirefoxDriver();
    firefoxDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    jsChrome = (JavascriptExecutor) chromeDriver;
    jsFirefox = (JavascriptExecutor) firefoxDriver;

    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    chromeDriver.quit();
    firefoxDriver.quit();
  }
  public String waitForWindow(int timeout, WebDriver driver ) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }

  @Test
  public void trustStandard() throws InterruptedException {
    test(chromeDriver, jsChrome);
    test(firefoxDriver, jsFirefox);
  }
  public void test(WebDriver driver, JavascriptExecutor js) {

    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));

    WebElement link = driver.findElement(By.xpath("//a[4]"));
    js.executeScript("arguments[0].click();", link);

    WebElement inputButton1 = driver.findElement(By.xpath("//div[2]/input"));
    js.executeScript("arguments[0].click();", inputButton1);

    WebElement inputElement1 = driver.findElement(By.xpath("//div[2]/input"));
    inputElement1.sendKeys("zinchen_ko@mail.ru");

    WebElement inputElement2 = driver.findElement(By.xpath("//div[3]/input"));
    inputElement2.sendKeys("zinchen_ko@mail.ru");

    WebElement inputButton2 = driver.findElement(By.xpath("//div[5]/input"));
    js.executeScript("arguments[0].click();", inputButton2);

    WebElement inputElement3 = driver.findElement(By.xpath("//div[5]/input"));
    inputElement3.sendKeys("500");

    vars.put("window_handles", driver.getWindowHandles());

    WebElement submit = driver.findElement(By.xpath("//div[9]/input"));
    js.executeScript("arguments[0].click();", submit);

    vars.put("win1289", waitForWindow(2000, driver));
    driver.switchTo().window(vars.get("win1289").toString());

    Assert.assertTrue(driver.getCurrentUrl().startsWith("https://unitpay.ru"));
  }
}
