package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LinkstestTest {
  private WebDriver chromeDriver, firefoxDriver;
  JavascriptExecutor jsChrome, jsFirefox;
  private Map<String, Object> vars;
  @Before
  public void setUp() {
    chromeDriver = new ChromeDriver();
    chromeDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    firefoxDriver = new FirefoxDriver();
    firefoxDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    jsChrome = (JavascriptExecutor) chromeDriver;
    jsFirefox = (JavascriptExecutor) firefoxDriver;

    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    chromeDriver.quit();
    firefoxDriver.quit();
  }

  @Test
  public void trustStandard() throws InterruptedException {
    test(chromeDriver, jsChrome);
    test(firefoxDriver, jsFirefox);
  }
  public void test(WebDriver driver, JavascriptExecutor js) throws InterruptedException {

    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    
    WebElement link1 = driver.findElement(By.xpath("//a[2]"));
    Thread.sleep(2000);
    js.executeScript("arguments[0].click();", link1);
    Assert.assertTrue(driver.getCurrentUrl().startsWith("https://xtool.ru/backlinks"));

    WebElement link2 = driver.findElement(By.xpath("//div[2]/div[2]/div/ul/li/a"));
    Thread.sleep(2000);
    js.executeScript("arguments[0].click();", link2);
    Assert.assertTrue(driver.getCurrentUrl().startsWith("https://xtool.ru/backlinks"));

    WebElement link3 = driver.findElement(By.xpath("//div[2]/div[2]/div/ul/li[2]/a"));
    Thread.sleep(2000);
    js.executeScript("arguments[0].click();", link3);
    Assert.assertTrue(driver.getCurrentUrl().startsWith("https://xtool.ru/backlinks"));

    WebElement link4 = driver.findElement(By.xpath("//div[2]/div[2]/div/ul/li[3]/a"));
    Thread.sleep(2000);
    js.executeScript("arguments[0].click();", link4);
    Assert.assertTrue(driver.getCurrentUrl().startsWith("https://xtool.ru/backlinks"));

  }
}
