package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.*;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;


import java.time.Duration;
import java.util.*;

public class LoginTest {
    private WebDriver driver;
    Wait<WebDriver> wait;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().timeouts().scriptTimeout(Duration.ofMinutes(2));
        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));
        js = (JavascriptExecutor) driver;
        wait = new FluentWait<WebDriver>(driver)
                .withTimeout(Duration.ofSeconds(5))
                .pollingEvery(Duration.ofSeconds(3))
                .ignoring(NoSuchElementException.class);
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void registration()  {
        driver.get("https://xtool.ru/");
        driver.manage().window().setSize(new Dimension(1876, 1080));

        WebElement loginBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/a[2]"));
        js.executeScript("arguments[0].click();", loginBtn);

        WebElement emailInput = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[1]/input[1]"));
        emailInput.sendKeys("callmepedro@yandex.ru");

        WebElement passwordInput = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[1]/input[2]"));
        passwordInput.sendKeys("qwe123");

        WebElement enterBtn = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[2]/button[2]"));
        js.executeScript("arguments[0].click();", enterBtn);

        WebElement accountEmail = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/div/div[1]/div"));

        Assert.assertEquals(accountEmail.getText(), "callmepedro@yandex.ru");
    }
}
