package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.*;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;


import java.time.Duration;
import java.util.*;

public class LogoutTest {
    private WebDriver chromeDriver, firefoxDriver;
    JavascriptExecutor jsChrome, jsFirefox;
    @Before
    public void setUp() {
        chromeDriver = new ChromeDriver();
        chromeDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

        firefoxDriver = new FirefoxDriver();
        firefoxDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

        jsChrome = (JavascriptExecutor) chromeDriver;
        jsFirefox = (JavascriptExecutor) firefoxDriver;
    }
    @After
    public void tearDown() {
        chromeDriver.quit();
        firefoxDriver.quit();
    }
    @Test
    public void logout() throws InterruptedException {
        test(firefoxDriver, jsFirefox);
        test(chromeDriver, jsChrome);
    }
    public void test(WebDriver driver, JavascriptExecutor js) throws InterruptedException {
        driver.get("https://xtool.ru/");
        driver.manage().window().setSize(new Dimension(1876, 1080));

        WebElement loginBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/a[2]"));
        js.executeScript("arguments[0].click();", loginBtn);

        Thread.sleep(500);

        WebElement emailInput = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[1]/input[1]"));
        emailInput.sendKeys("callmepedro@yandex.ru");

        WebElement passwordInput = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[1]/input[2]"));
        passwordInput.sendKeys("qwe123");

        WebElement enterBtn = driver.findElement(By.xpath("/html/body/div[1]/div/div/form/div[2]/button[2]"));
        js.executeScript("arguments[0].click();", enterBtn);

        Thread.sleep(500);

        WebElement accountBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/div/div[2]/div[2]/a"));
        js.executeScript("arguments[0].click();", accountBtn);

        Thread.sleep(500);

        WebElement logoutBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/div/div[2]/div[2]/a"));
        js.executeScript("arguments[0].click();", logoutBtn);

        WebElement regBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/a[1]"));
        Assert.assertTrue(regBtn.isDisplayed());
    }
}
