package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.*;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;


import java.time.Duration;
import java.util.*;

public class RegistrationTest {
    private WebDriver driver;
    Wait<WebDriver> wait;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        driver.manage().timeouts().scriptTimeout(Duration.ofMinutes(2));
        driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(10));
        js = (JavascriptExecutor) driver;
        wait = new FluentWait<WebDriver>(driver)
                .withTimeout(Duration.ofSeconds(5))
                .pollingEvery(Duration.ofSeconds(3))
                .ignoring(NoSuchElementException.class);
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void registration()  {
        driver.get("https://xtool.ru/");
        driver.manage().window().setSize(new Dimension(1876, 1080));

        WebElement registerBtn = driver.findElement(By.xpath("/html/body/nav/div/div/div[2]/a[1]"));
        js.executeScript("arguments[0].click();", registerBtn);

        WebElement emailInput = driver.findElement(By.xpath("/html/body/main/div/div[2]/form/table/tbody/tr/td/input"));
        emailInput.sendKeys("callmepedro@yandex.ru");

        WebElement agreement = driver.findElement(By.xpath("/html/body/main/div/div[2]/form/input[1]"));
        js.executeScript("arguments[0].click();", agreement);

        WebElement regBtn = driver.findElement(By.xpath("/html/body/main/div/div[2]/form/input[2]"));
        js.executeScript("arguments[0].click();", regBtn);

        Alert alert = wait.until(ExpectedConditions.alertIsPresent());
        Assert.assertEquals(alert.getText(), "Данный e-mail уже зарегестрирован в системе");
    }
}
