package lab3;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TrustSearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
  @Test
  public void trustSearch() {
    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1876, 1080));
    driver.findElement(By.xpath("//main/div/form/div/input")).click();
    driver.findElement(By.xpath("//main/div/form/div/input")).sendKeys("https://www.tune-it.ru/");
    driver.findElement(By.xpath("//button[contains(.,\'Проверить\')]")).click();
  }
}
