package lab3;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class TrustPagerankTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void trustPagerank() {
    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1876, 1080));
    WebElement inputElement = driver.findElement(By.xpath("/html/body/main/div[1]/form/div/input"));
    inputElement.sendKeys("https://www.tune-it.ru/");

    driver.findElement(By.xpath("//main/div/form/div/input")).click();
    driver.findElement(By.xpath("//main/div/form/div/input")).sendKeys("https://www.tune-it.ru/");
    driver.findElement(By.xpath("//main/div/form/div/button")).click();
  }
}
