package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.*;

public class TrustPagerankTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1876, 1080));
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void trustPagerank() {

    WebElement inputElement = driver.findElement(By.xpath("/html/body/main/div[1]/form/div/input"));
    inputElement.sendKeys("https://www.tune-it.ru/");

    WebElement pagerankCheckbox = driver.findElement(By.xpath("/html/body/main/div[1]/div[3]/div[2]/input"));
    js.executeScript("arguments[0].click();", pagerankCheckbox);

    WebElement searchBtn = driver.findElement(By.xpath("/html/body/main/div[1]/form/div/button"));
    js.executeScript("arguments[0].click();", searchBtn);

    WebElement siteUrl= driver.findElement(By.xpath("/html/body/main/div/div[2]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[2]/span"));
    Assert.assertEquals(siteUrl.getText(), "www.tune-it.ru");
  }
}
