package lab3;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.firefox.FirefoxDriver;


import java.time.Duration;

public class TrustStandardTest {
  private WebDriver chromeDriver, firefoxDriver;
  JavascriptExecutor jsChrome, jsFirefox;
  @Before
  public void setUp() {
    chromeDriver = new ChromeDriver();
    chromeDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    firefoxDriver = new FirefoxDriver();
    firefoxDriver.manage().timeouts().implicitlyWait(Duration.ofSeconds(15));

    jsChrome = (JavascriptExecutor) chromeDriver;
    jsFirefox = (JavascriptExecutor) firefoxDriver;
  }
  @After
  public void tearDown() {
    chromeDriver.quit();
    firefoxDriver.quit();
  }
  @Test
  public void trustStandard() throws InterruptedException {
    test(chromeDriver, jsChrome);
    test(firefoxDriver, jsFirefox);
  }

  public void test(WebDriver driver, JavascriptExecutor js) {
    driver.get("https://xtool.ru/");
    driver.manage().window().setSize(new Dimension(1876, 1080));

    WebElement inputElement = driver.findElement(By.xpath("/html/body/main/div[1]/form/div/input"));
    inputElement.sendKeys("https://www.tune-it.ru/");

    WebElement searchBtn = driver.findElement(By.xpath("/html/body/main/div[1]/form/div/button"));
    js.executeScript("arguments[0].click();", searchBtn);

    WebElement siteUrl= driver.findElement(By.xpath("/html/body/main/div/div[2]/div[2]/div[1]/div[2]/div/div[2]/div[1]/div[2]/span"));
    Assert.assertEquals(siteUrl.getText(), "www.tune-it.ru");
  }

}
